apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: chatbot-dec6-1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/maysunfaisal/chatbot-dec6-1:81d6a5161a6538cf53c61ce58cc83f9036178c84@sha256:5278808ee7c33ec6e3f3c42034ca342a1e23cad4244004f66f39a479ab96bcce # use pre-built to bootstrap 
          name: app-inference
